/* Webify.af — English */
window.WEBIFY_LANGS = window.WEBIFY_LANGS || {};
window.WEBIFY_LANGS.en = {
    code:"en", dir:"ltr", htmlLang:"en", name:"EN",
    meta:{home:"Home",about:"About Us",projects:"Projects",experience:"Experience",contact:"Contact",vps:"Virtual Private Servers",hosting:"Web Hosting",services:"Software Services",pricing:"Pricing",support:"Support",login:"Client Login",webDesign:"Website Design",laravel:"Laravel Development",mobile:"Mobile Development",database:"Database Design"},
    brand:{name:"Webify",tld:".af",tag:"Software Development • Hosting • VPS"},
    topbar:{phone:"+93 79 000 0000",email:"hello@webify.af",status:"All systems operational"},
    theme:{toggle:"Toggle light/dark theme"},
    header:{portal:"Client Portal",start:"Get Started",menu:"Menu",close:"Close",navAria:"Main navigation"},
    nav:{home:"Home",pricing:"Pricing",support:"Support",
        company:{label:"Company",blurb:"Who we are — our story, experience and work",
            card:{title:"Built in Kabul",desc:"From idea to global product, with a team from Afghanistan.",cta:"About us"},
            items:{about:{t:"About Us",d:"Our story, values and team"},experience:{t:"Experience",d:"Career path, freelancing and open source"},projects:{t:"Projects",d:"Portfolio and GitHub repositories"},contact:{t:"Contact Us",d:"Start a conversation"}}},
            services:{label:"Services",blurb:"Custom software, hosting and virtual servers",
                card:{title:"Webify Cloud Infrastructure",desc:"99.9% uptime and 24/7 support.",cta:"Get started"},
                groups:{
                    infra:{t:"Infrastructure",items:{
                            hosting:{t:"Web Hosting",d:"Shared, cloud and managed WordPress"},
                            vps:{t:"VPS Servers",d:"Dedicated resources with NVMe storage"}
                        }},
                    dev:{t:"Development",items:{
                            software:{t:"Software Services",d:"Web, mobile and SaaS products"},
                            webDesign:{t:"Website Design",d:"UI/UX, responsive and SEO-focused"},
                            laravel:{t:"Laravel Development",d:"Enterprise systems and SaaS with Laravel"},
                            mobile:{t:"Mobile Development",d:"iOS & Android with Flutter"},
                            database:{t:"Database Design",d:"Schema, optimization and migration"}
                        }}
                }}},
    common:{from:"From",perMonth:"/ mo",popular:"Most Popular",learnMore:"Learn more",monthly:"Monthly",yearly:"Yearly",saveTip:"-20%",send:"Send",required:"This field is required",invalidEmail:"Enter a valid email",formOk:"Your message has been received; we will reply soon.",demo:"Demo",code:"Code",choose:"Select",plan:"Plan",specs:"Specs",price:"Price"},
    home:{
        slides:[
            {img:"webify-saas-dashboard",kicker:"Our mission: SaaS products",title:"We build software\nthat grows with you",cap:"From idea to launch — design, development and hosting of SaaS products by the Webify team.",cta:{t:"Software Services",href:"services.html"}},
            {img:"webify-datacenter-racks",kicker:"NVMe Virtual Servers",title:"Real speed, dedicated resources",cap:"VPS with NVMe storage, a stable network and delivery in minutes.",cta:{t:"VPS Plans",href:"vps.html"}},
            {img:"webify-fiber-network",kicker:"Web Hosting",title:"Reliable hosting for your website",cap:"Shared, cloud and managed WordPress plans with daily backups.",cta:{t:"Hosting Plans",href:"hosting.html"}},
            {img:"webify-dev-team-kabul",kicker:"The Webify Team",title:"Your technical partner, from Kabul to the world",cap:"International experience in development, freelancing and open-source projects.",cta:{t:"Meet the team",href:"about.html"}}],
        stats:[{n:120,s:"+",l:"Projects delivered"},{n:99.9,s:"%",l:"Uptime SLA"},{n:40,s:"+",l:"Active clients"},{n:8,s:"",l:"Years of experience"}],
        svc:{kicker:"What we do",title:"The three pillars of Webify",sub:"Our main goal is building SaaS products — with hosting and servers right alongside.",
            items:[
                {ic:"rocket",t:"SaaS & Software Development",d:"Design and build of web, mobile and cloud products.",href:"services.html"},
                {ic:"server",t:"Web Hosting",d:"Fast, secure hosting with a simple panel and daily backups.",href:"hosting.html"},
                {ic:"cloud",t:"Virtual Servers",d:"VPS with dedicated resources, NVMe and full root access.",href:"vps.html"}]},
        why:{kicker:"Why Webify",title:"Software and infrastructure, under one roof",sub:"When the builder of your software also hosts it, everything is faster and more stable.",img:"webify-office-work",
            items:[
                {t:"Full ownership",d:"Your code and data always belong to you; no lock-in."},
                {t:"Scalable from day one",d:"Our architecture grows with your users."},
                {t:"Trilingual support",d:"In Dari, Pashto and English, around the clock."},
                {t:"Multi-layer security",d:"Firewall, monitoring, backups and free SSL certificates."}]},
        stack:{kicker:"Technologies",title:"The tools we build with every day",items:["TypeScript","Node.js","React","Vue","Laravel","PostgreSQL","Docker","Kubernetes","Redis","LiteSpeed","CloudLinux","cPanel"]},
        teaser:{kicker:"Virtual Servers",title:"VPS from $4 per month",sub:"Instant delivery, NVMe storage and real support.",
            items:[{name:"VPS Starter",spec:"2 vCPU • 2GB RAM • 40GB NVMe",price:"$4"},{name:"VPS Developer",spec:"4 vCPU • 8GB RAM • 120GB NVMe",price:"$16"},{name:"VPS Business",spec:"8 vCPU • 16GB RAM • 240GB NVMe",price:"$32"}],
            cta:{t:"All plans",href:"vps.html"}},
        testi:{kicker:"Testimonials",title:"Trust we have earned",
            items:[
                {q:"Webify's SaaS platform fully automated our subscription management.",n:"Ahmad Nawid",r:"CEO, Aria Logistics"},
                {q:"The servers are stable and support truly responds — even at midnight.",n:"Freshta Rahmani",r:"Tech Lead, Pamir Store"},
                {q:"From design to deployment, everything was transparent and on time.",n:"Maryam Rahimi",r:"Founder, Taaleemyar"}]},
        band:{t:"Build your next project with us",d:"From a landing page to a full SaaS product — we are ready.",a1:{t:"Talk to us",href:"contact.html"},a2:{t:"View pricing",href:"pricing.html"}}},
    about:{
        hero:{kicker:"About Webify",title:"A team that takes software seriously",sub:"Developers, infrastructure engineers and designers gathered to build products that last."},
        pnLabel:"About us",pn:[{id:"story",l:"Our Story"},{id:"values",l:"Values"},{id:"stack",l:"Technologies"},{id:"philosophy",l:"Philosophy"},{id:"team",l:"Team"}],
        story:{kicker:"Our story",title:"From Kabul, for the world",
            p1:"Webify started with a simple idea: developers in Afghanistan should be able to deliver services at the level of major global companies. Today we build SaaS products and run our own hosting infrastructure.",
            p2:"Our team has worked with international clients, freelance projects and open-source contributions — a mix that gives us a practical, standards-driven perspective.",
            img:"webify-team-story",facts:[{n:8,s:"",l:"Years of development"},{n:120,s:"+",l:"Projects"},{n:6,s:"",l:"Client countries"}]},
        values:{kicker:"Our values",title:"How we work",
            items:[{ic:"shield",t:"Technical honesty",d:"We recommend the right solution, not the most expensive one."},{ic:"chart",t:"Measurable quality",d:"We define success criteria for every project."},{ic:"globe",t:"Global standards",d:"Code, security and infrastructure follow best practices."},{ic:"headset",t:"Long-term partnership",d:"We stay with you after delivery."}]},
        stack:{kicker:"Technologies",title:"Our tech stack",sub:"The tools we go deep with.",
            groups:[{t:"Development",items:["TypeScript","Node.js","React","Vue","Laravel","Flutter"]},{t:"Data & Infrastructure",items:["PostgreSQL","MySQL","Redis","Docker","Kubernetes","Linux"]},{t:"Hosting",items:["LiteSpeed","CloudLinux","cPanel/WHM","Nginx","AlmaLinux","OpenLiteSpeed"]}]},
        phil:{kicker:"Software philosophy",title:"Our beliefs about building products",lead:"Good software is not an accident; it is the result of small, correct decisions.",quote:"“Simplify the problem first, then build the beautiful solution.”",
            items:[{t:"Problem first, code second",d:"Before writing a single line, we clarify the problem with you."},{t:"Scalable simplicity",d:"We prefer simple architecture; complexity has a cost."},{t:"Security by design",d:"Security is not a phase; it flows through every layer."},{t:"Continuous delivery",d:"Small, steady releases instead of big, risky launches."}]},
        team:{kicker:"Team",title:"The faces of Webify",members:[{n:"Farid Ahmadi",r:"Lead Developer & Founder"},{n:"Maryam Rahimi",r:"Product & UI/UX Designer"},{n:"Omar Khaldi",r:"DevOps & Infrastructure Engineer"},{n:"Setara Nazari",r:"Full-stack Developer"}]}},
    projects:{
        hero:{kicker:"Portfolio",title:"Projects we are proud of",sub:"A mix of SaaS products, web applications and open-source repositories."},
        pnLabel:"Projects",pn:[{id:"grid",l:"Portfolio"},{id:"repos",l:"GitHub Repos"},{id:"case",l:"Case Study"}],
        filters:{all:"All",saas:"SaaS",web:"Web",mobile:"Mobile",oss:"Open Source"},
        items:[
            {t:"Daftar Cloud Accounting",cat:"saas",d:"A SaaS accounting platform for small businesses with subscription billing.",tags:["Vue","Node.js","PostgreSQL"],img:"webify-saas-accounting"},
            {t:"Sehat Online Clinic",cat:"saas web",d:"Appointment booking and e-prescription system for clinics.",tags:["React","Laravel"],img:"webify-clinic-app"},
            {t:"Pamir Marketplace",cat:"web",d:"Multi-vendor e-commerce store with local payment gateway.",tags:["Laravel","Vue"],img:"webify-ecommerce-store"},
            {t:"Smart Lycee",cat:"mobile",d:"School management app for students and parents.",tags:["Flutter","Firebase"],img:"webify-school-app"},
            {t:"af-docs Library",cat:"oss",d:"Open-source documentation generator with Persian/Dari and RTL support.",tags:["TypeScript"],img:"webify-oss-docs"},
            {t:"Aria Logistics Dashboard",cat:"saas web",d:"Live shipment tracking and fleet management.",tags:["React","Node.js","Redis"],img:"webify-logistics-dashboard"}],
        none:"No items found.",
        repos:{kicker:"GitHub",title:"Our public repositories",sub:"A slice of the team's open-source contributions.",cta:{t:"GitHub profile",href:"#"},
            items:[{n:"webify/af-docs",d:"Lightweight docs generator with RTL and Dari support.",lang:"TypeScript",stars:214,forks:38},{n:"webify/lite-cache",d:"Cache layer compatible with Redis and Memcached.",lang:"PHP",stars:156,forks:22},{n:"webify/rtl-kit",d:"Ready-made UI components for RTL applications.",lang:"TypeScript",stars:342,forks:61}]},
        case:{kicker:"Case study",title:"Subscription automation for Aria Logistics",client:"Aria Logistics — 2025",img:"webify-case-logistics",
            d:"Their legacy system managed subscriptions and payments manually. We built a SaaS platform that automated invoicing, renewals and reporting.",
            results:[{n:70,s:"%",l:"Less manual work"},{n:3,s:"×",l:"Subscriber growth"},{n:99.9,s:"%",l:"Uptime since launch"}],
            quote:{q:"Webify was not just a developer; they were our business partner.",n:"Ahmad Nawid, CEO"},cta:{t:"Request a similar project",href:"contact.html"}}},
    experience:{
        hero:{kicker:"Experience",title:"The road we have travelled",sub:"A blend of company work, international freelancing and open source."},
        pnLabel:"Experience",pn:[{id:"timeline",l:"Timeline"},{id:"freelance",l:"Freelancing"},{id:"oss",l:"Open Source"}],
        timeline:[
            {period:"2023 — Now",role:"Founder & Lead Developer",org:"Webify.af",d:"Building SaaS products, running hosting infrastructure and leading a team of six.",tags:["SaaS","DevOps","Leadership"]},
            {period:"2021 — 2023",role:"Full-stack Developer",org:"Freelancer — EU & Gulf clients",d:"40+ web and mobile projects; from storefronts to enterprise systems.",tags:["React","Laravel","Flutter"]},
            {period:"2019 — 2021",role:"Software Engineer",org:"Aria Tech, Kabul",d:"Developed enterprise systems and maintained Linux servers.",tags:["Linux","MySQL","Vue"]},
            {period:"2017 — 2019",role:"Web Developer (Intern → Junior)",org:"Local startups",d:"Started with PHP and JavaScript, contributing to small projects.",tags:["PHP","JavaScript"]}],
        free:{kicker:"Freelancing",title:"Working with global clients",d:"Years of experience on international platforms with a focus on quality and on-time delivery.",stats:[{n:40,s:"+",l:"International projects"},{n:100,s:"%",l:"Client satisfaction"}],
            platforms:[{n:"Upwork",d:"Top Rated in web development"},{n:"Fiverr",d:"SaaS and API packages"},{n:"Direct",d:"Long-term direct contracts"}]},
        oss:{kicker:"Open source",title:"Open-source contributions",sub:"We give back what we take from the community.",
            items:[{n:"af-docs",d:"Docs generator with RTL support",stars:214,href:"#"},{n:"rtl-kit",d:"UI kit for RTL apps",stars:342,href:"#"},{n:"lite-cache",d:"Lightweight cache for PHP",stars:156,href:"#"}]}},
    contact:{
        hero:{kicker:"Contact",title:"Let's start a conversation",sub:"Have an idea, a project or a question? Our team usually replies within 24 hours."},
        pnLabel:"Contact",pn:[{id:"form",l:"Contact Form"},{id:"info",l:"Contact Info"},{id:"links",l:"Professional Links"}],
        form:{kicker:"Contact form",title:"Write to us",name:"Full name",ph_name:"Your name",email:"Email",ph_email:"you@example.com",subject:"Subject",ph_subject:"e.g. Building a SaaS app",message:"Message",ph_message:"Tell us about your project…",send:"Send message"},
        info:{kicker:"Information",title:"Ways to reach us",emailL:"Email",phoneL:"Phone",addrL:"Address",addr:"Kabul, Afghanistan — Shahre Naw",hoursL:"Working hours",hours:"Sat–Thu, 8:00–17:00"},
        links:{kicker:"Links",title:"Follow us",items:[{n:"GitHub",d:"Our repositories and contributions",href:"#"},{n:"LinkedIn",d:"The team's professional network",href:"#"},{n:"X (Twitter)",d:"News and updates",href:"#"}]},
        map:{alt:"Webify location map"}},
    vps:{
        hero:{kicker:"Virtual Servers",title:"Powerful VPS with transparent pricing",sub:"Dedicated resources, NVMe storage and instant delivery — from personal projects to enterprise scale."},
        pnLabel:"VPS",pn:[{id:"tiers",l:"Plans"},{id:"specs",l:"Specifications"},{id:"features",l:"Features"},{id:"faq",l:"FAQ"}],
        tiers:{kicker:"Plans",title:"VPS tiers",sub:"All plans include root access and a dedicated IPv4.",note:"Prices are in USD; card and remittance payments accepted.",
            items:[
                {name:"VPS Starter",desc:"For personal projects and testing",price:4,hot:false,specs:[{k:"vCPU",v:"2 cores"},{k:"RAM",v:"2 GB"},{k:"NVMe",v:"40 GB"},{k:"Traffic",v:"1 TB"}],feats:["Full root access","Weekly snapshots","Basic support"]},
                {name:"VPS Developer",desc:"Developers' favourite",price:16,hot:true,specs:[{k:"vCPU",v:"4 cores"},{k:"RAM",v:"8 GB"},{k:"NVMe",v:"120 GB"},{k:"Traffic",v:"4 TB"}],feats:["Daily snapshots","Managed firewall","Priority support"]},
                {name:"VPS Business",desc:"For production applications",price:32,hot:false,specs:[{k:"vCPU",v:"8 cores"},{k:"RAM",v:"16 GB"},{k:"NVMe",v:"240 GB"},{k:"Traffic",v:"8 TB"}],feats:["Off-server daily backups","24/7 monitoring","99.9% SLA"]},
                {name:"VPS Enterprise",desc:"Custom architecture at scale",price:64,hot:false,specs:[{k:"vCPU",v:"16 cores"},{k:"RAM",v:"32 GB"},{k:"NVMe",v:"480 GB"},{k:"Traffic",v:"Unmetered"}],feats:["Dedicated architecture","Dedicated account manager","99.99% SLA"]}]},
        specs:{kicker:"Specifications",title:"Technical comparison",cols:["Feature","Starter","Developer","Business","Enterprise"],
            rows:[{f:"CPU",v:["2 vCPU","4 vCPU","8 vCPU","16 vCPU"]},{f:"Memory",v:["2 GB","8 GB","16 GB","32 GB"]},{f:"NVMe storage",v:["40 GB","120 GB","240 GB","480 GB"]},{f:"Monthly traffic",v:["1 TB","4 TB","8 TB","Unmetered"]},{f:"Dedicated IPs",v:["1","1","2","4"]},{f:"Backups",v:["—","Daily","Daily + off-site","Daily + off-site"]}]},
        feat:{kicker:"Features",title:"Included with every server",
            items:[{ic:"bolt",t:"Instant delivery",d:"Your server is ready in under 5 minutes."},{ic:"shield",t:"Firewall & DDoS",d:"Multi-layer protection against attacks."},{ic:"cpu",t:"Real NVMe",d:"Enterprise NVMe drives, not SATA."},{ic:"globe",t:"Stable network",d:"Multiple upstream paths for availability."},{ic:"refresh",t:"Snapshots",d:"Roll back to a previous state with one click."},{ic:"headset",t:"Real support",d:"A technical team, not canned replies."}]},
        faq:{kicker:"FAQ",title:"VPS questions & answers",
            items:[{q:"Which operating systems are supported?",a:"Ubuntu, Debian, AlmaLinux and Rocky Linux; custom ISO installation is also possible."},{q:"Can I upgrade without downtime?",a:"Yes, RAM and disk upgrades usually happen without a reinstall."},{q:"What payment methods do you accept?",a:"International bank cards, USDT and local remittance."},{q:"Do you offer managed servers?",a:"Yes, a full management package (setup, security, updates) can be added."}]}},
    hosting:{
        hero:{kicker:"Web Hosting",title:"Fast, painless hosting",sub:"From personal sites to busy stores — with LiteSpeed, daily backups and free SSL."},
        pnLabel:"Hosting",pn:[{id:"plans",l:"Plans"},{id:"compare",l:"Compare"},{id:"wp",l:"Managed WordPress"},{id:"faq",l:"FAQ"}],
        plans:{kicker:"Plans",title:"Hosting plans",sub:"All plans include free SSL and daily backups.",
            items:[
                {name:"Shared Start",desc:"For personal & brochure sites",price:2,hot:false,feats:["5 GB NVMe","1 website","Unlimited email","Free SSL","Daily backups"]},
                {name:"Cloud Pro",desc:"For growing businesses",price:7,hot:true,feats:["25 GB NVMe","Unlimited websites","Dedicated cloud resources","Built-in CDN","Priority support"]},
                {name:"Managed WordPress",desc:"WordPress without the hassle",price:12,hot:false,feats:["40 GB NVMe","Auto core & plugin updates","LiteSpeed cache","Login protection","Free site migration"]}]},
        compare:{kicker:"Compare",title:"Which plan is right for you?",cols:["Feature","Shared Start","Cloud Pro","Managed WP"],
            rows:[{f:"NVMe space",v:["5 GB","25 GB","40 GB"]},{f:"Websites",v:["1","Unlimited","3"]},{f:"Dedicated resources",v:["Shared","Yes","Yes"]},{f:"WordPress optimisation",v:["—","—","Yes"]},{f:"CDN",v:["—","Yes","Yes"]},{f:"Support",v:["Standard","Priority","Priority + WP expert"]}]},
        wp:{kicker:"Managed WordPress",title:"Your WordPress, our management",d:"We handle updates, security, caching and backups so you can focus purely on content.",img:"webify-wordpress-managed",
            feats:["Secure automatic updates","Dedicated LiteSpeed cache","Off-server daily backups","Free migration from your old host"],cta:{t:"Start with Managed WordPress",href:"contact.html"}},
        faq:{kicker:"FAQ",title:"Hosting questions & answers",
            items:[{q:"Do you migrate my site for free?",a:"Yes, migration from any other host is free and without downtime."},{q:"Which control panel do you use?",a:"Standard cPanel with one-click application installers."},{q:"What happens if I exceed my traffic?",a:"Your site stays online; we contact you about upgrading."},{q:"Is there a money-back guarantee?",a:"Yes, a full refund within 30 days."}]}},
    services:{
        hero:{kicker:"Software Services",title:"From idea to product, with one team",sub:"Design, development, deployment and maintenance — our core focus is building SaaS products."},
        pnLabel:"Services",pn:[{id:"caps",l:"Capabilities"},{id:"process",l:"Process"},{id:"saas",l:"SaaS Focus"},{id:"stack",l:"Tech Stack"}],
        caps:{kicker:"Capabilities",title:"What we build",sub:"The six core areas of the Webify team.",
            items:[{ic:"code",t:"Web Applications",d:"Dashboards, admin panels and enterprise systems."},{ic:"rocket",t:"SaaS Products",d:"Multi-tenant architecture, subscription billing and scale."},{ic:"phone",t:"Mobile Apps",d:"iOS and Android with Flutter or React Native."},{ic:"plug",t:"APIs & Integrations",d:"API design, payment gateways and system integrations."},{ic:"cloud",t:"DevOps & Cloud",d:"CI/CD, Docker, Kubernetes and monitoring."},{ic:"pen",t:"UI/UX Design",d:"Research, wireframes and beautiful, functional interfaces."}]},
        proc:{kicker:"Process",title:"How we work",
            steps:[{t:"Discover",d:"Discovery sessions, problem definition and success criteria."},{t:"Design",d:"System architecture and user interface design."},{t:"Build",d:"Agile development with weekly demos."},{t:"Test & Deploy",d:"Automated testing, deployment and initial monitoring."},{t:"Support",d:"Maintenance, updates and new feature development."}]},
        saas:{kicker:"Core focus",title:"Why SaaS?",d:"SaaS means stable revenue for you and a better experience for users. We build multi-tenant products designed for billing, scale and security from day one.",img:"webify-saas-build",
            feats:["Multi-tenant architecture","Billing & subscriptions","Customer management dashboard","Scale-ready infrastructure"],cta:{t:"Free SaaS consultation",href:"contact.html"}},
        stack:{kicker:"Technologies",title:"Services tech stack",items:["TypeScript","Node.js","React","Vue","Laravel","Flutter","PostgreSQL","Redis","Docker","Kubernetes","AWS","Hetzner"]}},
    pricing:{
        hero:{kicker:"Pricing",title:"Transparent pricing, no surprises",sub:"All hosting, VPS and software service rates compared in one place."},
        pnLabel:"Pricing",pn:[{id:"hosting",l:"Hosting"},{id:"vps",l:"VPS"},{id:"svc",l:"Software Services"}],
        hosting:{kicker:"Hosting",title:"Hosting plans",rows:[{name:"Shared Start",m:2,y:1.6,f:"5 GB NVMe • 1 site"},{name:"Cloud Pro",m:7,y:5.6,f:"25 GB NVMe • unlimited sites"},{name:"Managed WordPress",m:12,y:9.6,f:"40 GB NVMe • fully managed"}]},
        vps:{kicker:"VPS",title:"VPS plans",rows:[{name:"VPS Starter",m:4,y:3.2,f:"2 vCPU • 2 GB RAM"},{name:"VPS Developer",m:16,y:12.8,f:"4 vCPU • 8 GB RAM"},{name:"VPS Business",m:32,y:25.6,f:"8 vCPU • 16 GB RAM"},{name:"VPS Enterprise",m:64,y:51.2,f:"16 vCPU • 32 GB RAM"}]},
        svc:{kicker:"Software services",title:"Development rates",rows:[{name:"Custom development",d:"Hourly coding by a senior developer",price:25,unit:"per hour"},{name:"SaaS MVP build",d:"Launch-ready first version in 8–12 weeks",price:3500,unit:"per project"},{name:"Monthly maintenance",d:"Updates, security, backups and support",price:150,unit:"per month"}]},
        note:"Yearly rates include a 20% discount. All prices are in USD."},
    support:{
        hero:{kicker:"Support",title:"Here whenever you need us",sub:"Documentation, FAQs and a ticketing system — in your own language."},
        pnLabel:"Support",pn:[{id:"docs",l:"Documentation"},{id:"faq",l:"FAQ"},{id:"ticket",l:"Tickets"},{id:"status",l:"System Status"}],
        search:{ph:"Search the FAQs…"},
        docs:{kicker:"Knowledge base",title:"Documentation & guides",
            items:[{ic:"book",t:"Getting Started",d:"Guide to connecting hosting and VPS",n:"12 articles"},{ic:"dollar",t:"Billing",d:"Payments, invoices and renewals",n:"8 articles"},{ic:"key",t:"Client Portal",d:"Learn the management panel and tickets",n:"6 articles"},{ic:"code",t:"API Docs",d:"Hosting API and automation",n:"10 articles"}]},
        faq:{kicker:"FAQ",title:"Quick answers",
            items:[{q:"How do I open a ticket?",a:"From the client portal, in the support section, choose “New ticket”."},{q:"What is the response time?",a:"Normal tickets within 12 hours; emergencies under 1 hour."},{q:"Do you offer phone support?",a:"Yes, during office hours and 24/7 for critical issues."},{q:"How do I back up my site?",a:"Daily automatic backups are active; you can also take manual backups from the control panel."},{q:"How long does DNS take to propagate?",a:"Usually under an hour, maximum 24 hours."},{q:"Do you help install applications?",a:"Yes, installing common apps is free on managed plans."}]},
        none:"No results found.",
        ticket:{kicker:"Tickets",title:"Need an urgent answer?",d:"Our ticketing system is live in the client portal; or email us directly.",cta:{t:"Open a ticket",href:"#"},mail:"support@webify.af"},
        status:{kicker:"Status",title:"Live service status",d:"Follow uptime, incidents and announcements on the status page.",pill:"All systems operational",cta:{t:"Status page",href:"#"}}},
    login:{
        hero:{kicker:"Client Portal",title:"Sign in to your account",sub:"Manage services, invoices and support tickets in one place."},
        form:{emailL:"Email",passL:"Password",ph_email:"you@example.com",ph_pass:"Your password",remember:"Remember me",forgot:"Forgot password?",submit:"Sign in",or:"or sign in with",noAcc:"Don't have an account?",signup:"Request a new account"},
        side:{kicker:"Unified portal",title:"Every service, one dashboard",d:"Manage hosting, VPS, invoices and tickets from a single panel."},
        perks:[
            {ic:"shield",t:"Two-factor authentication",d:"Account security with 2FA and secure login."},
            {ic:"server",t:"Service management",d:"Provision, upgrade and monitor hosting and VPS."},
            {ic:"dollar",t:"Invoices & billing",d:"Online payments and full history."},
            {ic:"headset",t:"Support tickets",d:"Track requests with a clear SLA."}]},
    webDesign:{
        hero:{kicker:"Website Design",title:"A website that sells, not just shows",sub:"Modern UI, fully responsive and optimised for search engines."},
        pnLabel:"Web design",pn:[{id:"caps",l:"Capabilities"},{id:"deliverables",l:"Deliverables"},{id:"process",l:"Process"},{id:"stack",l:"Technologies"},{id:"faq",l:"FAQ"}],
        caps:{kicker:"What we design",title:"Website design services",
            items:[{ic:"pen",t:"UI/UX design",d:"User research, wireframes and a polished visual interface."},{ic:"globe",t:"Responsive",d:"Great experience on mobile, tablet and desktop."},{ic:"chart",t:"Technical SEO",d:"Speed, structure and structured data."},{ic:"rocket",t:"Performance",d:"Green Core Web Vitals and sub-2-second loads."},{ic:"shield",t:"Baseline security",d:"HTTPS, security headers and login protection."},{ic:"refresh",t:"Maintenance",d:"Content updates, backups and monitoring."}]},
        dlv:{kicker:"Deliverables",title:"What you receive",
            items:[
                {num:"01",ic:"pen",t:"Visual design",d:"Final design in Figma with every page.",pts:["Extensible design system","Colour palette & typography","Light & dark modes"]},
                {num:"02",ic:"code",t:"Front-end code",d:"HTML/CSS/JS or React/Vue components.",pts:["Clean, documented code","Fully responsive","WCAG accessibility"]},
                {num:"03",ic:"rocket",t:"Launch & SEO",d:"Deployed on your hosting with optimisation.",pts:["Domain & SSL setup","Meta & schema","Initial performance report"]}]},
        proc:{kicker:"Process",title:"From brief to launch",
            steps:[{t:"Discover",d:"Brand, audience and goals session."},{t:"Wireframe",d:"Page structure and user flows."},{t:"Visual design",d:"Final design in Figma with your feedback."},{t:"Develop",d:"Responsive build and cross-device testing."},{t:"Launch",d:"Deployment, training and 30 days free support."}]},
        stack:{kicker:"Technologies",title:"Design and build tools",items:["Figma","HTML5","CSS3","Tailwind","React","Vue","Next.js","Nuxt","GSAP","Framer Motion"]},
        faq:{kicker:"FAQ",title:"Web design questions",
            items:[{q:"How long does a design project take?",a:"Usually 3 to 6 weeks depending on pages and complexity."},{q:"Do you design WordPress sites too?",a:"Yes — both static/SPA sites and custom WordPress."},{q:"Do you provide copy and images?",a:"Copywriting and stock photography are available on request."},{q:"What support is included after delivery?",a:"30 days of free support for bug fixes and minor changes."}]},
        band:{t:"Your next design, with us",d:"From a single landing page to a full corporate site.",a1:{t:"Start a project",href:"contact.html"},a2:{t:"See portfolio",href:"projects.html"}}},
    laravel:{
        hero:{kicker:"Laravel Development",title:"Stable systems with Laravel",sub:"SaaS, APIs and enterprise panels built on one of PHP's most mature frameworks."},
        pnLabel:"Laravel",pn:[{id:"caps",l:"What we build"},{id:"features",l:"Features"},{id:"int",l:"Integrations"},{id:"process",l:"Process"},{id:"faq",l:"FAQ"}],
        caps:{kicker:"What we build",title:"Our Laravel projects",
            items:[{ic:"rocket",t:"SaaS products",d:"Multi-tenant architecture with subscriptions and billing."},{ic:"plug",t:"RESTful APIs",d:"OpenAPI docs and JWT/Sanctum auth."},{ic:"code",t:"Admin panels",d:"Filament or custom dashboards for your team."},{ic:"chart",t:"Reporting",d:"Analytical dashboards with Laravel queues."},{ic:"shield",t:"Auth systems",d:"Login, roles and permissions with Breeze/Jetstream."},{ic:"refresh",t:"Legacy migration",d:"Move from raw PHP or older frameworks."}]},
        feat:{kicker:"Features",title:"Why Laravel is our choice",
            items:[{ic:"bolt",t:"Fast development",d:"Artisan, Eloquent and a standard structure."},{ic:"shield",t:"Built-in security",d:"CSRF, XSS and SQL-injection protection."},{ic:"cpu",t:"Queues & cache",d:"Horizon for queues and Redis for cache."},{ic:"globe",t:"Testable",d:"Pest/PHPUnit with automated CI."},{ic:"plug",t:"Rich ecosystem",d:"Filament, Livewire, Inertia and Vapor."},{ic:"refresh",t:"Easy maintenance",d:"Clear structure and thorough docs."}]},
        int:{kicker:"Integrations",title:"Connect to any service",
            items:[{ic:"dollar",n:"Stripe",d:"Payments & subscriptions"},{ic:"plug",n:"PayPal",d:"Global payments"},{ic:"mail",n:"SendGrid",d:"Transactional email"},{ic:"phone",n:"Twilio",d:"SMS & voice"},{ic:"cloud",n:"AWS S3",d:"File storage"},{ic:"code",n:"GitHub",d:"CI/CD"},{ic:"chart",n:"Google Analytics",d:"Tracking"},{ic:"shield",n:"Cloudflare",d:"Security & CDN"}]},
        proc:{kicker:"Process",title:"How we ship a Laravel project",
            steps:[{t:"Analyse",d:"Requirements, data model and APIs."},{t:"Architect",d:"Design modules and database."},{t:"Develop",d:"Agile coding with weekly reviews."},{t:"Test",d:"Unit, feature and E2E before release."},{t:"Deploy",d:"Docker + CI/CD on your infrastructure."}]},
        faq:{kicker:"FAQ",title:"Laravel questions",
            items:[{q:"Which Laravel version do you use?",a:"Always the current LTS — Laravel 11 today."},{q:"Do you work with a specific front-end?",a:"Inertia + Vue/React or Livewire, depending on need."},{q:"Do you upgrade existing projects?",a:"Yes, version upgrades and performance improvements."},{q:"What is the monthly maintenance cost?",a:"From $150 for the base package; details on the pricing page."}]},
        band:{t:"Your next system on Laravel",d:"From MVP to a mature SaaS product.",a1:{t:"Book a consultation",href:"contact.html"},a2:{t:"Pricing",href:"pricing.html"}}},
    mobile:{
        hero:{kicker:"Mobile Development",title:"iOS and Android apps, one codebase",sub:"Cross-platform with Flutter and React Native — faster delivery, lower cost."},
        pnLabel:"Mobile",pn:[{id:"caps",l:"Capabilities"},{id:"tech",l:"Technology"},{id:"process",l:"Process"},{id:"feat",l:"Features"},{id:"faq",l:"FAQ"}],
        caps:{kicker:"Capabilities",title:"The apps we build",
            items:[{ic:"phone",t:"Consumer apps",d:"Stores, social and entertainment."},{ic:"rocket",t:"SaaS apps",d:"Mobile companion to your cloud product."},{ic:"code",t:"Enterprise apps",d:"Internal tools for staff and logistics."},{ic:"chart",t:"Mobile dashboards",d:"Reports and monitoring on the move."},{ic:"plug",t:"Hardware integration",d:"Bluetooth, GPS, camera and NFC."},{ic:"shield",t:"Secure apps",d:"End-to-end encryption and biometrics."}]},
        tech:{kicker:"Technology",title:"Our mobile stack",
            items:[{ic:"phone",n:"Flutter",d:"First choice for beautiful UI"},{ic:"code",n:"React Native",d:"Best for JS teams"},{ic:"shield",n:"Firebase",d:"Auth, push and analytics"},{ic:"cloud",n:"Supabase",d:"PostgreSQL + realtime"},{ic:"plug",n:"REST & GraphQL",d:"Connect to any backend"},{ic:"refresh",n:"Fastlane",d:"Automated releases"},{ic:"chart",n:"Sentry",d:"Error monitoring"},{ic:"cpu",n:"CI/CD",d:"GitHub Actions"}]},
        proc:{kicker:"Process",title:"The app-building path",
            steps:[{t:"Define",d:"Personas, user stories and roadmap."},{t:"UX design",d:"Wireframes and main flows."},{t:"UI & prototype",d:"Visual design and clickable prototype."},{t:"Develop",d:"Two-week sprints with TestFlight."},{t:"Release",d:"App Store and Google Play."}]},
        feat:{kicker:"Features",title:"Standard features in our apps",
            items:[{ic:"shield",t:"Biometric auth",d:"Fingerprint and Face ID."},{ic:"refresh",t:"Offline mode",d:"Automatic sync when reconnected."},{ic:"bolt",t:"Push notifications",d:"Firebase Cloud Messaging."},{ic:"globe",t:"Multilingual",d:"RTL support and Dari/Pashto."},{ic:"cpu",t:"Performance",d:"60fps and instant loads."},{ic:"chart",t:"Behaviour analytics",d:"Firebase Analytics & Mixpanel."}]},
        faq:{kicker:"FAQ",title:"Mobile questions",
            items:[{q:"Flutter or React Native?",a:"Flutter for bespoke UI, React Native for JS ecosystems."},{q:"Do you build a web version too?",a:"Yes — Flutter Web and React Native Web are supported."},{q:"Do you handle App Store release?",a:"Yes, we manage the full submission and review flow."},{q:"What post-launch support is included?",a:"A monthly maintenance package covering SDK updates and bug fixes."}]},
        band:{t:"Build your app idea",d:"From MVP to apps with millions of users.",a1:{t:"Book a consultation",href:"contact.html"},a2:{t:"Pricing",href:"pricing.html"}}},
    database:{
        hero:{kicker:"Database Design",title:"A foundation that scales",sub:"Schema design, migration, optimisation and management of relational and NoSQL databases."},
        pnLabel:"Database",pn:[{id:"caps",l:"Services"},{id:"tech",l:"Technologies"},{id:"schema",l:"Sample schema"},{id:"process",l:"Process"},{id:"faq",l:"FAQ"}],
        caps:{kicker:"Services",title:"What we do",
            items:[{ic:"db",t:"Schema design",d:"Normalised, scale-ready data modelling."},{ic:"refresh",t:"Data migration",d:"Zero-downtime moves from legacy systems."},{ic:"bolt",t:"Query optimisation",d:"Indexing and response-time reduction."},{ic:"shield",t:"Data security",d:"Encryption, backups and least-privilege access."},{ic:"chart",t:"Analytics & reporting",d:"Materialised views and OLAP."},{ic:"plug",t:"Integration",d:"ETL, CDC and sync pipelines."}]},
        tech:{kicker:"Technologies",title:"Databases we work with",
            items:[{ic:"db",n:"PostgreSQL",d:"First choice for SaaS"},{ic:"db",n:"MySQL",d:"Compatible and widespread"},{ic:"db",n:"MongoDB",d:"Document-oriented data"},{ic:"cpu",n:"Redis",d:"Cache and queues"},{ic:"cloud",n:"ElasticSearch",d:"Text search"},{ic:"bolt",n:"ClickHouse",d:"Big-data analytics"},{ic:"shield",n:"CockroachDB",d:"Distributed and resilient"},{ic:"refresh",n:"TimescaleDB",d:"Time-series data"}]},
        schema:{kicker:"نمونه",title:"یک اسکیما چگونه دیده می‌شود",titleTbl:"users — نمونه",
            cols:["ستون","نوع","توضیح"],
            rows:[
                {c:"id",t:"bigint",n:"کلید اصلی",pk:true},
                {c:"email",t:"varchar(255)",n:"یکتا، ایندکس‌شده"},
                {c:"password_hash",t:"varchar(255)",n:"bcrypt"},
                {c:"role",t:"enum",n:"user, admin"},
                {c:"created_at",t:"timestamptz",n:"default now()"},
                {c:"deleted_at",t:"timestamptz",n:"حذف نرم"}
            ]},
        proc:{kicker:"Process",title:"The database design path",
            steps:[{t:"Discover",d:"Requirements, entities and relationships."},{t:"Model",d:"ER diagram and normalisation."},{t:"Implement",d:"Migrations and seeders."},{t:"Optimise",d:"EXPLAIN, indexes and partitions."},{t:"Monitor",d:"Performance dashboards and alerts."}]},
        faq:{kicker:"FAQ",title:"Database questions",
            items:[{q:"PostgreSQL or MySQL?",a:"For SaaS and complex data we recommend PostgreSQL."},{q:"Do you recommend NoSQL too?",a:"Yes — MongoDB or ElasticSearch for catalogues, logs and search."},{q:"Do you set up automatic backups?",a:"Yes — daily backups plus WAL archive for point-in-time recovery."},{q:"What about migrating from Oracle or SQL Server?",a:"We have experience migrating to PostgreSQL with tools such as Ora2Pg."}]},
        band:{t:"Reset your database foundation",d:"From a fresh design to optimising an existing system.",a1:{t:"Free consultation",href:"contact.html"},a2:{t:"Pricing",href:"pricing.html"}}},
    footer:{
        blurb:"Webify is a team of software developers focused on SaaS products, hosting and virtual servers.",
        news:{t:"Newsletter",ph:"Your email",btn:"Subscribe",ok:"Subscription registered. Thank you!"},
        cCompany:{t:"Company",links:[{t:"About Us",href:"about.html"},{t:"Blog",href:"#"},{t:"Contact",href:"contact.html"},{t:"Testimonials",href:"index.html#testimonials"}]},
        cLegal:{t:"Legal",links:[{t:"Terms of Service",href:"#"},{t:"Privacy Policy",href:"#"},{t:"Acceptable Use Policy (AUP)",href:"#"},{t:"SLA Agreement",href:"#"}]},
        cInfra:{t:"Infrastructure",links:[{t:"Datacenter Locations",href:"#"},{t:"Network Looking Glass",href:"#"},{t:"System Status Page",href:"#"}]},
        rights:"© 2026 Webify.af — All rights reserved.",made:"Designed & built in Kabul, Afghanistan"}
};